### ISSUE TITLE
Minor issues and enhancements in the metrics module

### ISSUE THREAD

**Issue by bockthom** [se-sic/coronet#181]
### Description

In the metrics module `util-metrics.R`, there are some minor inconsistencies which should be fixed:

**(1) `metrics.avg.pathlength`:**
This function takes three parameters: `network`, `directed`, `unconnected`. However, there are no default values for `directed` and `unconnected`, which lets the `igraph::average.path.length` function crash if these parameters are not passed to the function.
Suggestion: Add default values for those parameters.

In addition, the description of the `unconnected` parameter seems to be wrong as it states the opposite:
```R
#' @param unconnected whether all vertices of the network are connected
```
It is also not clear what happens when this parameter is `TRUE` or `FALSE`. Maybe we should add more information from igraph's description of this parameter.

**(2) Default values:**
Most of the `metrics.*` functions have parameters which take default values. However, in many cases, the default values are missing in the parameter documentation, which violates our [contribution guidelines](https://github.com/se-passau/coronet/blob/master/CONTRIBUTING.md#r-coding-conventions).

**(3) `is.smallworld`:**
We do have a function `metrics.scale.freeness` returning several numerical values and its boolean version `metrics.is.scale.free`.
However, for small worldness, we only have the function `metrics.smallworldness`, which returns a numerical value, but no boolean version. There is just a comment in the documentation saying `is.smallworld = s.delta > 1`. Why not moving that into a boolean function `metrics.is.smallworld` like we have it for scale freeness?

**(4) `metrics.smallworldness`:**
This function crashes with an error 
```R
Error in .Call("R_igraph_erdos_renyi_game", as.numeric(n), as.numeric(type1), : At games.c:681 : Invalid number (too large) of edges, Invalid value
```
or something similar if you pass a non-simplified network to this function. It is stated in the documentation that the network needs to be simplified, but it would be a better option to also add a check to this function and stop with a reasonable error message if the network is not simplified, just to make debugging easier...

**Comment by bockthom** [comment]
In addition to the above mentioned problems, there are additional problems regarding some corner cases, which should be fixed also:

 **(5) `metrics.hub.degree`:**
When passing an empty network (i.e., a network without vertices) to this function, the function leads to an error. However, instead, we handle this case within this function and return an appropriate value instead (e.g., print a warning and return `NA`).

**(6) Integrate centrality functions into `util-metrics`:**
When someone is interested into centrality values (not into the classification results but into the plain numbers), at the moment, we have to compute the classification and get the actual centrality values in a complex way afterwards, using the following statements:
```R
class = get.author.class.by.type(network = net, proj.data = data, type = "network.eigen",
                                 restrict.classification.to.authors = data$get.authors.by.data.source(data.sources)[["name"]])
centrality = rbind(class$core, class$peripheral)[,2]
```
Instead of doing that manually all the time, we should provide a function that directly returns the centrality values (e.g., `metrics.vertex.centralities` or something similar).
However, we need to find a solution on how to determine the `data.source` for the `restrict.classification.to.authors` parameter, as this might be tricky to determine and set it correctly. One idea would be to use the edge attribute `relation`, such as in the following way:
```R
relations = unique(igraph::E(net)$relation)
```
An then we have to do the following mappings: "cochange" -> "commits", "mail" -> "mails", "issue" -> "issues" for each of the (possibly multiple) relations we can have in one network. However, how should we deal with the relation `character(0)` which also could occur there (but first check when exactly this could occur). And also for artifact- or mutli-networks this could be problematic as we then not only have to consider authors, but also artifacts...
Nevertheless, in general, having such a function would help to avoid code duplication (and, hence, to avoid bugs) and to ease the computation of centrality values.

**Comment by nlschn** [comment]
Regarding point (4):
According to the [igraph manual](https://igraph.org/r/doc/erdos.renyi.game.html) of the function `erdos.renyi.game` is deprecated since version 0.8.0. However a `sessionInfo()` told me, that we are using igraph 1.2.6. 
My question is, should I leave it like that anyway or shall I look for replacement functions?

**Comment by bockthom** [comment]
> Regarding point (4):
> According to the [igraph manual](https://igraph.org/r/doc/erdos.renyi.game.html) of the function `erdos.renyi.game` is deprecated since version 0.8.0. However a `sessionInfo()` told me, that we are using igraph 1.2.6.

*You* are using igraph 1.2.6, and in our current cluster setup, we coincidentally also use igraph 1.2.6. However, we did not specify any requirements on the package version. That is, a potential user could use any version (I know that this is a very optimistic attitude, as interfaces etc. can change during package updates and we cannot really guarantee to support everything...)

> My question is, should I leave it like that anyway or shall I look for replacement functions?

Anyway, please have a look at the replacement function and if there is a difference, then we can discuss here whether this is relevant or not.
In general, we often use igraph functions that are declared as "deprecated" on purpose. For example, some time ago, igraph adjusted its naming scheme and introduced new names for a bunch of existing functions. For instance, `vcount` and `ecount` have been replaced by something else––but in our opinion the new name is rather confusing and not that obvious:  `vcount` clearly states that we count vertices, but the new name (which I actually don't remember any more) sounded less intuitive to us. Hence, we decided to go with the old function names––for better readability and also for backwards compatibility. As long as just the name has changed and the implementation stays pretty much the same, there is no need to replace such functions.

**Comment by nlschn** [comment]
That makes sense. I will take a look at the functions proposed by the manual. Tank you.

**Comment by bockthom** [comment]
Unfortunately, I have been very imprecise in my description of part **(6) Integrate centrality functions into `util-metrics`** of this issue. I am sorry for that. As this part is quite confusing (as today's discussion has shown), I will provide some detailed examples here:

What we would like to have is a function which provides us with a centrality value for each vertex. However, we should consider two different, well-known use cases, as a baseline for our discussions regarding the `restrict.classification.to.authors` parameter.
So, let's consider the following exemplary commit history:

```R
Developer "A" has created File "X" in 1980.
In 2020, developer "B" changes file "X".
Afterwards, also 2020, developers "C" and "D" both change file "X". 
```
When we use this example scenario and perform splitting with a time-window of one year, we get the following to results, depending on whether we use data-based or network-based splitting:

| Example  | network-based splitting    | data-based splitting    |
|---------|--------------------:| --------------------------:|
| Range Network <br> (result of splitting)        | A ←(2020)– B <br> C –(2020)→ B <br> D –(2020)→ B <br> D –(2020)→ C                   | <br> C –(2020)→ B <br> D –(2020)→ B <br> D –(2020)→ C                 |
| Range Data (commits only) <br> (result of splitting)             | <table><tr><th>Author</th><th>Date</th><th>Changed Artifact</th></tr><tr><td>B<br>C<br>D</td><td>2020 <br> 2020 <br> 2020</td> <td>X<br> X<br> X</td></tr></table>                   | <table><tr><th>Author</th><th>Date</th><th>Changed Artifact</th></tr><tr><td>B<br>C<br>D</td><td>2020 <br> 2020 <br> 2020</td> <td>X<br> X<br> X</td></tr></table>                 |
| Restrict classification <br> to active developers *(expected)*:                 | `[B, C, D]`                   | `[B, C, D]`                 |
| *Current default* for parameter `restrict.classification...` <br> is ```NULL```, resulting in classifying these authors when using **network-based classification** types: | `[A, B, C, D]`                   | `[B, C, D]`  |
| Restrict classification to authors present in data using `data$get.authors.by. data.source("commits")[["name"]]`*(suggestion for the new default)*:  | `[B, C, D]`                   | `[B, C, D]`                 |

As this example shows: Edge-based splitting (and also unsplit, global data) would not be affected by the suggested default value. However, network-based splitting would be affected by the suggested default and would be closer to the expected results.

There only is one dangerous situation: If isolates have been removed from the network before, then some authors could show up in the classification which are not present in the network but solely in the data. But remember, this can only happen to removed isolates. Anyway, these don't distort the classification, as authors not appearing in the network, and therefore also not appearing in the network-based classification, will get an `NA` centrality value, see the following code lines: https://github.com/se-sic/coronet/blob/a7f4123dcb86a7a0f76adf791b66a7d9c24f7647/util-core-peripheral.R#L216-L226 Hence, this should also not be a problem. Otherwise, if someone draws the conclusion that this might be problematic, we also could remove `NA` values or make that configurable via a parameter having an appropriate default value :wink: 

Nevertheless, I would like to add a few additional constraints for the new suggested behavior:
- The new default value for `restrict.classification.to.authors` should only be applied if both `network` and `data` are supplied to the centrality function. If only one of these parameter are supplied (and the other one is `NULL` per default), then the default value does not have an effect: If we only pass the network, there is no data to restrict the authors to. If we only pass the data, applying the restriction does not have any effect as the restriction results in the same authors as without restriction. (Hence, we could also think about using this as the new default for the function `get.author.class.by.type`.)
- The new centrality function should only be applicable for network-based classification types, for several reasons:
    1. The function is added to the metrics module as this module contains only network metrics and centrality is definitively a network metric :wink: 
    2. Centrality on count-based data is not really centrality. We can classify on count-based data, but this just returns counts and not normalized centrality values.
    3. If one would like to get the "centrality" values (i.e., counts) for count-based classifications, one could just call functions such as [`get.author.commit.count`](https://github.com/se-sic/coronet/blob/a7f4123dcb86a7a0f76adf791b66a7d9c24f7647/util-core-peripheral.R#L740). So, we just need this centrality function for network-based classification types, where a centrality computation is involved.

---

Btw, @nlschn, we should make sure that the data frame which is to be returned by the new function is ordered similarly like in the above linked count function: Order by centrality (desc) (and then name (asc) in the case that multiple authors have the same centrality value). However, this can be achieved by plain R functions, I guess there is no need for using sqldf here. And we should also make sure that the ordering deals with `NA` values correctly, that is, places them at the end of the data frame. This should already be the case, but we should check that, and if it is not the case, make sure that the ordering will be correct.

---

In addition, I would like to add another important point to this discussion––this can also be part of a future PR, but we should already think about that and prepare the new function for potential future extensions: Shouldn't we make this new function more generic, to be applied to other networks than author networks? As we add the new function to the networks metrics module, I would suggest to use generic names for parameters and variables and names: Use "vertex" instead of "author", use just "name" instead of "author.name". Then we could easily apply this function also to artifact networks which could have files as vertices. There would be no need to change this function even more (even if it internally calls `get.author.class.by.type`). However, in such a case, the default vertex restriction should not be applied as it won't make sense. But I guess we could also find a way to infer that from the given network (as part of a future enhancement).

---

Last but not least, there is the question on how to determine the correct data source when using `data$get.authors.by.data.source(data.sources)[["name"]]` for vertex restriction (regardless of whether this is the new default or not):

From the edge attribute `relation` we can get the relations of the networks (`"cochange", "mail", "issue"`): ```unique(igraph::E(net)$relation)```. We then can map the relations to data sources, as in the following example:

```R
 data.source = switch(unique(E(net)$relation),
                         cochange = "commits",
                         mail = "mails",
                         issue = "issues")
```
However, this example does not work, as there can be multiple relations in one network (the above example assumes that there is only one). In general, dealing with multiple relations should be similar: For each relation appearing in the network, we add an element to the `data.sources` vector which is passed to `get.authors.by.data.source`––and this function in turn can deal with multiple data sources :smile: 

Unfortunately, I cannot reproduce the situation where `character(0)` is appearing in the edge attribute `relation`. I've spent the last hours on that but I was not able to reproduce this with any project... I will further investigate on this next week, stay tuned. For the moment, let's assume that this cannot happen.

---

Sorry for adding such a long comment containing that many different aspects and details. I hope this level of details helps to better understand what we have tried to discuss today. I suggest that everyone who reads this comment reflects about it during the next week––if you have different suggestions or other reasonable objections I might have missed, replies to this comment are welcome :bulb: 

Anyway, let's finally discuss this next week and make decisions on this in our meeting.
