### ISSUE TITLE
"How-to" example in the README.md currently leads to an error when plotting the created network

### ISSUE THREAD

**Issue by bockthom** [se-sic/coronet#186]
In the README file of coronet, we have included a ["How-to"](https://github.com/se-passau/coronet#how-to) section containing a short example on how to build a (bipartite) network. However, when executing the code taken from this example, we end-up in an error when plotting the bipartite network:
```R
> plot.network(bpn)
Error in graph_to_tree(graph, mode = direction) : Graph must be directed

```
Thanks to @wabosh for pointing that out.

After searching for that error message on the Web, I found out that this problem is not related to whether the given network is directed or undirected, but it is "just" a problem of a missing layout specification when using `ggraph`. Hence, we need to adjust the layout specification in the internals of the `plot.network` function of coronet:
    
    1) When creating a ggraph object, we already need to explicitly specify
       the layout we want to use. As we rely on igraph and its layouts,
       we use 'layout = "igraph"' and then we have to specify the concrete
       layout algorithm from igraph (as 'algorithm' paramater).
    
    2) Opposed to previous layout specification, now a layout name has to be
       stated instead of naming a layout function. Unfortunately, there is
       no official list of supported igraph layouts. Hence, we need to rely
       on the following table (which comes from python and not from R):
       https://igraph.org/python/doc/tutorial/tutorial.html#layout-algorithms
       Notice that the layout algorithm needs to be given as string in form of
       the 'short name' given in this table. However, if there are multiple
       short names specified in the table, only one of them might actually
       work for ggraph.
    
    Now as before, the default layout is 'kk' (kamada kawai). If one wants
    to use another igraph layout, just set the igraph attribute 'layout' to
    the short name of the layout and then this one will be used for creating
    the ggraph object.

I have already implemented the above described fixes and with this fix the example from the "How-to" and especially the function call `plot.network(bpn)` works again :smile:
The fix will be incorporated into my current pull request and will hopefully be integrated into coronet soon.

**Comment by clhunsen** [comment]
What versions of the packages `igraph` and `ggraph` do you have installed, @bockthom?

I just tested your patch with versions `igraph==1.2.6` and `ggraph==2.0.4` (clean coronet installation on R 4.0.3) – and it did not work due to the error "_Error in as.igraphlayout(algorithm) : Cannot find igraph layout_". Actually, I could not reproduce your very problem in the first place (I tried by reverting your patch again). I guess and hope that there is some dependency problem somewhere as you definitely had different problems and proposed a patch. I just want to be sure that everything is evaluated correctly here. Please have a another look at this.

The following patch fixed it for me:
```patch
diff --git a/util-plot.R b/util-plot.R
index e8c2585..fdb6023 100644
--- a/util-plot.R
+++ b/util-plot.R
@@ -137,7 +137,7 @@ plot.get.plot.for.network = function(network, labels = TRUE) {
     layout.algorithm = igraph::get.graph.attribute(network, "layout")
 
     ## create a ggraph object using the specified igraph layout
-    p = ggraph::ggraph(network, layout = "igraph", algorithm = layout.algorithm)
+    p = ggraph::ggraph(network, layout = layout.algorithm)
 
     ## plot edges if there are any
     if (igraph::ecount(network) > 0) {
```
--------------------
As we are already talking about the showcase code: Addtionally, the suffix `.char` of some variables in the plot section needs to be removed as it is built upon some old vertex attributes.

**Comment by bockthom** [comment]
> What versions of the packages `igraph` and `ggraph` do you have installed, @bockthom?
I have used the installation which we already used for a couple of years:
`igraph==1.2.5` and `ggraph==2.0.3` (with R 3.6.3).

My implementation worked with these package versions. However, thanks for trying it with more recent package versions :+1: 
I just tried your fix in my setup (i.e., with the package versions I have stated above) and—against my expectations—it worked! So, as it works with our current setup and your more recent setup (which I will update my package versions to, soon, too), I am fine with your fix and will apply it soon (with you being the author of the commit). Thanks a lot again @clhunsen!

> Actually, I could not reproduce your very problem in the first place (I tried by reverting your patch again). I guess and hope that there is some dependency problem somewhere as you definitely had different problems and proposed a patch. I just want to be sure that everything is evaluated correctly here. Please have a another look at this.

That sounds weird. But did you try the "How to" example from the [README.md](https://github.com/se-passau/coronet#how-to) (**not** the ``showcase.R``)? Because there we plot an undirected bipartite network, and there we ran into the problems described above. After @wabosh has drawn my attention to that problem, I could reproduce the problem he had identified—so there are, at least, two persons who (re)produced this problem :wink: 
The problem might have occurred due to different package versions than you have used @clhunsen. Anyway, as my fix combined with your fix seems to work on even both kinds of installed package versions, I think we have a solution that should work.

---

> As we are already talking about the showcase code: Addtionally, the suffix `.char` of some variables in the plot section needs to be removed as it is built upon some old vertex attributes.

Thanks for spotting this, I will remove those no-longer-existing suffixes.
(I did not even think about having a look at the `showcase.R` to search for example use cases of plotting functions. Thanks for this hint, I definitively should look at the `showcase.R` more often, in the future!)

**Comment by clhunsen** [comment]
Thanks for trying my suggested patch! And for spotting this problem in the first place!

> That sounds weird. But did you try the "How to" example from the [README.md](https://github.com/se-passau/coronet#how-to) (**not** the `showcase.R`)?

Sorry, I forgot to add a corresponding sentence: Yes, I tried that and the READMEmd example *did not work* without your patch. 
I tried it again a moment ago and the solution for me is to use `"kk"` and setting the layout as in my suggested patch above when calling `ggraph::ggraph(...)`.

**Comment by bockthom** [comment]
Thanks again @clhunsen. I have applied your fix and now this should have fixed the issue (at least, for you and me). So, I will close this issue soon if there are no further comments. If the problem with the layout starts to appear again, we can reopen this issue :wink:
