### ISSUE TITLE
Add further vertex attributes for author vertices

### ISSUE THREAD

**Issue by bockthom** [se-sic/coronet#188]
### Description

Complementary to #92 and #170, we should also add further vertex attributes for author vertices that deal with other data sources than commits. At the moment, we (almost) only have commit-related vertex attributes for authors, such as
`add.vertex.attribute.commit.count.author`,
`add.vertex.attribute.commit.count.committer` (and several more of them combining author and committer information),
`add.vertex.attribute.artifact.count` (only for source-code artifacts (files, functions, etc.)

Along with them, we need to create new functions to determine 
- [x] `mail.count`, 
- [x] `mail.thread.count`, 
- [x] `issue.count` (possibly also PR count?) , 
- [x] `issue.comment.count`, etc... 

*[The idea of this issue is rather old, but it has not been documented properly yet. So I just opened this issue to not forget about it.]*

### Ideas for the Implementation
To get the mail count etc. as values, we need new functions like `get.author.mail.count`. To achieve that, see also the following comment: https://github.com/se-sic/coronet/issues/70#issuecomment-424668069

For the implementation of the vertex attributes, see the current implementations for the commit-count attribute [L156ff](https://github.com/se-sic/coronet/blob/91fc448bad64dd17fa96a720322fe7d46337cc43/util-networks-covariates.R#L156ff) and for the artifact-count attribute [L385ff](https://github.com/se-sic/coronet/blob/91fc448bad64dd17fa96a720322fe7d46337cc43/util-networks-covariates.R#L385ff).

**Comment by JoJoDeveloping** [comment]
> For the implementation of the vertex attributes, see the current implementations for the commit-count attribute [L156ff](https://github.com/se-sic/coronet/blob/91fc448bad64dd17fa96a720322fe7d46337cc43/util-networks-covariates.R#L156ff) and for the artifact-count attribute [L385ff](https://github.com/se-sic/coronet/blob/91fc448bad64dd17fa96a720322fe7d46337cc43/util-networks-covariates.R#L385ff).

Where are these functions actually called from?

**Comment by bockthom** [comment]
> Where are these functions actually called from?

These functions are called by the end-user of coronet :smile: That is, they are not called inside coronet but are called by outside scripts which use coronet as a library.

However, if you are looking for example use cases, you can find an exemplary code snippet in our `showcase.R` file -- which just displays how to use vertex attributes in general, not using each of these functions, but the usage is very similar for all of these functions: https://github.com/se-sic/coronet/blob/91fc448bad64dd17fa96a720322fe7d46337cc43/showcase.R#L160-L179

In addition to that, these functions are also tested properly and therefore, of course, called in our test-suite: [test-networks-covariates.R](https://github.com/se-sic/coronet/blob/master/tests/test-networks-covariates.R)

Does this answer your question? If you need further information, don't hesitate to ask.
