### ISSUE TITLE
Various bugs or inconsistencies regarding the data, conf, and network modules

### ISSUE THREAD

**Issue by bockthom** [se-sic/coronet#197]
While reflecting on #177, I spotted the following issues:

1. The function [`reset.environment()` in the ProjectData class](https://github.com/se-sic/coronet/blob/bf8b331cd874f6fef787af0a6ad69c2a0496d3bb/util-data.R#L542) does not reset all the data, as `mails.patchstacks` is missing. (In addition, check if something else is missing there.)
2. The function [`reset.environment()` in the NetworkBuilder class](https://github.com/se-sic/coronet/blob/bf8b331cd874f6fef787af0a6ad69c2a0496d3bb/util-networks.R#L557) does not reset all the data, as `artifacts.network.mail` and `artifacts.network.issue` are missing. (In addition, check if something else is missing there.)
3. The documentation of the function [`check.value` in the Conf class](https://github.com/se-sic/coronet/blob/bf8b331cd874f6fef787af0a6ad69c2a0496d3bb/util-conf.R#L102) is incomplete, as the description of the return value is wrong, as, for instance, the value of `updatable` is missing, and not all values are returned always.
4. A comment in the function `get.pasta` of the data module is misleading:    "no storage" makes us believe that mails might not be stored, which is actually wrong. Instead, we should just state "no assignment", as the mails are not assigned to any variable here in this function.
    https://github.com/se-sic/coronet/blob/bf8b331cd874f6fef787af0a6ad69c2a0496d3bb/util-data.R#L919-L920
5. When calling the function `update.pasta.data`, a warning is printed that one should think about calling the cleanup function:
    https://github.com/se-sic/coronet/blob/bf8b331cd874f6fef787af0a6ad69c2a0496d3bb/util-data.R#L425-L426 However, this warning is also printed when calling the cleanup function itself, as the cleanup function in turn calls the update function. To prevent this silly behavior (which would end up in an endless recursion if the user would call the cleanup function again and again due to this warning), we could try to only print this warning of the function is **not** called by the cleanup function. I am not sure if this is possible, but it might be worth a try. @nlschn you already have some experience in finding out what the parent function call was (remember your work regarding on the `match.arg.or.default` function), you could check whether this would be possible here. If so, we should also check for the other cleanup functions whether we also end up in such silly warnings there.

**Comment by nlschn** [comment]
> I am not sure if this is possible, but it might be worth a try.

It is indeed possible and actually fairly easy to do.
