### ISSUE TITLE
Tests for identical outcome of different kinds of generating the same network

### ISSUE THREAD

**Issue by bockthom** [se-sic/coronet#86]
There are different ways to generate the same networks, in some cases. We should check that the outcome is the same for all ways.

---
Example: Generate bipartite networks and author networks using time-based splitting.

Network generation 1:

1.  construct bipartite network
2.  construct author network
3.  `split.networks.time.based` (maybe here we have to make sure to use the same bins for both bipartite and author network splitting)

Network generation 2:
1. construct multi network
2. `split.network.time.based`
3. `extract.author.network.from.network` with `remove.isolates = TRUE`
4. `extract.bipartite.network.from.network` with `remove.isolates = TRUE`

Check whether the generated lists of bipartite and author networks are identical for both generations.

---

We should test this with different kinds of relations (mail, cochange, issue) and different kinds of networks (bipartite, author, artifacts).

In addition, are there similar cases where we can construct the same networks using different construction algorithms?

--- 

In addition, consider also this comment: https://github.com/se-sic/coronet/issues/86#issuecomment-901992429

**Comment by bockthom** [comment]
When addressing this issue, we should also think about what happens in the following case:
Add two different vertex attributes to the same list of networks, but in a different order. Should this make a difference? Should the resulting networks be equal or not? Let's try what happens in this case and whether this is what we expect...

(For edge attributes, we already made sure that they are ordered...)

**Comment by bockthom** [comment]
Just to briefly summarize our today's meeting @joba00002: After you will have finished working on #141 (and potentially restructuring the division of tests into files), please have a look at my [last comment here in this issue](https://github.com/se-sic/coronet/issues/86#issuecomment-901992429) and design a test for that one. Afterwards, please check for which different kinds of relations (mail, cochange, issue) and different kinds of networks (bipartite, author, artifacts) we have already tests. If you have collected this information, then we can see which combinations are missing and decide for which combinations it would make sense to add tests and for which rather not.

**Comment by joba00002** [comment]
> Add two different vertex attributes to the same list of networks, but in a different order. Should this make a difference? Should the resulting networks be equal or not? Let's try what happens in this case and whether this is what we expect...

The order of the attributes is indeed different. However, I don't think this really matters, as I don't see how the order might be relevant.

> (For edge attributes, we already made sure that they are ordered...)

We could do the same here, for consistency.

**Comment by bockthom** [comment]
> > (For edge attributes, we already made sure that they are ordered...)
> 
> We could do the same here, for consistency.

Only if it is easily achievable, e.g., if there is a function in `igraph` that reorders vertex attributes. If the only option is to remove all the attributes and re-add them in the correct order, this is too inconvenient and we should keep everything as is (this only affects equality checks, e.g. in tests, anyway).
